version: "3"

services:
  app: 
    build: .
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=$PGHOST
      - DB_USER=$PGUSER
      - DB_PASSWORD=$PGPASSWORD
      - DB_NAME=$PGDATABASE
      - DB_PORT=$PGPORT
    volumes:  
      - .:/usr/app
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    env_file: ./.env 
    ports:
      - $LOCALPGPORT:$PGPORT
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE      

volumes:
  app:
  postgresdb: